name: Close Pull Request

# only trigger on pull request closed events
on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  merge_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
      - run: echo PR ${{ github.event.number }} has been closed
